language: python
python:
  - "3.2"
  - "3.3"
install:
  - "python setup.py install"
  - "pip install pylint"
script:
  - "pylint tests --errors-only"
  - "python -m doctest -v ./README.md"
  - "python -m unittest"