language: python
env:
  - CC=clang
  - CC=gcc
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - make install
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install pylint; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then make pylint; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then make doctest; else make test; fi
