language: python
python:
  - "3.1"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "python setup.py install"
# command to run tests
script:
  - "python doctests.py -v"
  - "python -m unittest"
